= Welcome to nixpkgs-jdk-ea

This GitHub Organization is a home for JDK EA pkgs for Nix. It contains a fork of https://github.com/NixOS/nixpkgs[nixos/nixpkgs].

The main repository for this Organization/Project is https://github.com/nixpkgs-jdk-ea/nixpkgs[nixpkgs-jdk-ea/nixpkgs]

The default branch `jdk-ea-25` of https://github.com/nixpkgs-jdk-ea/nixpkgs[nixpkgs-jdk-ea/nixpkgs] is an integration branch that makes available several JDK packages and updates to build tools like **Gradle** that support those JDKs.

== JDK Packages 

As of 2025-09-19 **JDK 25 is GA** (General Available) and at least three Java 25 JDKs have been merged to Nixpkgs `master`. This repository will be inactive until we decide to begin work on integrating EA builds of future JDKs.

You can check the current status of JDK 25 support in Nixpkgs by viewing the https://github.com/NixOS/nixpkgs/issues/430389[Java 25 Support Tracking Issue]

Depending upon interest and contributions from others, we may do the same thing for JDK 26 EA releases. Or perhaps we will wait until the next LTS version, JDK 29.

|===
|JDK |Package Name |Branch |Upstream PR

|Zulu
|zulu25
|merged
|PR :  https://nixpk.gs/pr-tracker.html?pr=443517[#443517]

|GraalVM CE
|graalvmPackages.graalvm-ce (25)
|merged
|PR : https://nixpk.gs/pr-tracker.html?pr=444049[#444049]

|Oracle GraalVM
|graalvmPackages.graalvm-oracle (25)
|merged
|PR https://nixpk.gs/pr-tracker.html?pr=443470[#443470]
|===

== Other Packages

The `jdk-ea-25` branch will also contain other packages such as build tools like **Gradle** that have been updated to support JDK 25.

|===
|Package Name |Version |Branch |Upstream PR

|gradle_9
|9.1.0
|`msgilligan/gradle-9.1.0`
|PR https://nixpk.gs/pr-tracker.html?pr=434086[#434086]
|===

== Getting Started

=== Using GraalVM 25 java and native-image

To test the GraalVM 25 JDK build from this project, you can use:

[source, bash]
----
nix shell github:nixpkgs-jdk-ea/nixpkgs/jdk-ea-25#graalvmPackages.graalvm-ce
----

NOTE:: Because PR https://github.com/NixOS/nixpkgs/pull/444049[#444049] was merged, you can now use a similar command on the upstream Nixpkgs `master` and soon on `nixpkgs-unstable`.

=== Using Gradle 9.1

[source, bash]
----
nix shell github:nixpkgs-jdk-ea/nixpkgs/jdk-ea-25#gradle_9
----

=== Building Java 25 code with Gradle 9.1 + GraalVM JDK 25

You'll need to use the following override in your nix configuration (e.g. devshell in `flake.nix`) to run Gradle with the newer JDK:

[source]
----
  (gradle_9.override {
      java = graalvmPackages.graalvm-ce;
   })
----

This will cause Gradle 9.1 to be launched with GraalVM JDK 25.

